# Generated by Django 3.2.8 on 2021-11-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=120)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('order placed', 'order placed'), ('Dispatched', 'Dispatched'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='order placed', max_length=120)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstoreapp.book')),
            ],
        ),
    ]
